### ISSUE TITLE
Last used „now playing“ App cannot be opened and is stuck on the launch screen.

### ISSUE THREAD

**Issue by mlgxyves** [Nosskirneh/RoadRunner-Public#6] opened 2020-04-18 22:18 UTC
As the title describes it sometimes happens that the last app with background playback can no longer be opened or is stuck on the launch screen. So far this has happened to me twice with Spotify and once with YouTube.

However, this bug can be fixed with a respring.

**Comment by Nosskirneh** [comment] 2020-04-19 07:23
Thanks for reporting!

I’ll try to reproduce this. I have an idea why it might be happening.

**Comment by Nosskirneh** [comment] 2020-04-29 20:16
I'm unable to reproduce it sadly.

Just so I understand correctly:
1. Play media from an app.
2. Respring. The app was excluded and media is still playing.
3. Attempting to open the app is not succeeded.

Prior to the respring, was the app in the background for a longer period?

**Comment by mlgxyves** [comment] 2020-04-29 21:29
I have now figured out what the problem should be.

This "Infinite launch screen" error occurs when the last used "Now Playing" app is open for too long in the background, where iOS would normally restart the app because the RAM is full but I think RoadRunner prevents this and causes that the app gets stuck in the launch screen.

The app can start normally again after a respring, but this happens to me 2-3 times a day and in the long run it's just annoying.

Here is an example of how the app is stuck on the launch screen.

[Example Video.zip](https://github.com/Nosskirneh/RoadRunner-Public/files/4554677/Example.Video.zip)

I am using an iPhone 11 on iOS 13.3.

**Comment by Nosskirneh** [comment] 2020-04-29 21:34
I see.

Is it correct that this only happens when the app has previously been excluded from a respring, media is paused and after opening/using of other apps for a while (to fill the RAM with stuff)?

**Comment by mlgxyves** [comment] 2020-04-29 21:43
In my experience, a respring does not cause this. I only meant that this bug can be fixed with a respring.

In my observation this only happens when the last used "now playing" app is paused and the RAM gets full so the app should normally restart but instead of restarting the App is stuck on the launchscreen.

I believe thats caused because RoadRunner usually wants to keep is the app in the background, but I'm not sure since I didn't program the tweak.

**Comment by Nosskirneh** [comment] 2020-04-29 21:46
Your guess might be correct. I'll try to see if I can reproduce these steps. Thanks for providing the details! :)

**Comment by Nosskirneh** [comment] 2020-05-04 18:13
Fixed in beta2. Thanks for providing intel necessary to reproduce and fix it!

**Closed as completed by Nosskirneh** 2020-05-04 18:13 UTC
